version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: eventure-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: eventure
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - eventure-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: eventure-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://root:password123@mongodb:27017/eventure?authSource=admin
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb
    networks:
      - eventure-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: eventure-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    env_file:
      - ./frontend/.env.local
    depends_on:
      - backend
    networks:
      - eventure-network

  nginx:
    image: nginx:alpine
    container_name: eventure-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    networks:
      - eventure-network

volumes:
  mongo_data:

networks:
  eventure-network:
    driver: bridge